create table if not exists public.products (
  id bigint generated by default as identity primary key,
  base_number text not null unique,
  name text not null,
  brand text not null default 'Merck',
  description text not null default '',
  synonyms text not null default '',
  cas text not null default '',
  sds_url text not null,
  source_url text not null,
  enrichment_status text not null default 'queued',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.variants (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  sku text not null unique,
  size text not null default 'Lihat spesifikasi',
  availability text not null default 'Indent',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists products_name_search_idx on public.products using gin (to_tsvector('simple', name || ' ' || base_number));
create index if not exists variants_product_id_idx on public.variants(product_id);

alter table public.products enable row level security;
alter table public.variants enable row level security;

drop policy if exists "public read products" on public.products;
create policy "public read products" on public.products for select to anon, authenticated using (true);
drop policy if exists "public read variants" on public.variants;
create policy "public read variants" on public.variants for select to anon, authenticated using (true);

revoke insert, update, delete on public.products from anon, authenticated;
revoke insert, update, delete on public.variants from anon, authenticated;

create or replace function public.search_catalog(search_text text default '', row_limit integer default 20, row_offset integer default 0)
returns table (
  id bigint, base_number text, name text, brand text, description text,
  synonyms text, cas text, sds_url text, source_url text,
  enrichment_status text, variants jsonb
)
language sql stable security invoker set search_path = public as $$
  with chosen as (
    select p.*
    from products p
    where coalesce(trim(search_text), '') = ''
       or p.name ilike '%' || search_text || '%'
       or p.base_number ilike '%' || search_text || '%'
       or exists (select 1 from variants v where v.product_id = p.id and v.sku ilike '%' || search_text || '%')
    order by p.name asc, p.id asc
    limit least(greatest(row_limit, 1), 51)
    offset greatest(row_offset, 0)
  )
  select p.id, p.base_number, p.name, p.brand, p.description, p.synonyms,
    p.cas, p.sds_url, p.source_url, p.enrichment_status,
    coalesce(jsonb_agg(jsonb_build_object('sku', v.sku, 'size', v.size, 'status', v.availability)
      order by v.sku) filter (where v.id is not null), '[]'::jsonb) variants
  from chosen p left join variants v on v.product_id = p.id
  group by p.id, p.base_number, p.name, p.brand, p.description, p.synonyms,
    p.cas, p.sds_url, p.source_url, p.enrichment_status
  order by p.name asc, p.id asc;
$$;

grant execute on function public.search_catalog(text, integer, integer) to anon, authenticated;
